llm:
  default_provider: gpt-4o-mini
  providers:
    ollama:
      type: ollama
      model: qwen2.5-coder:32b
      params:
        base_url: http://10.0.0.50:11434
    claude:
      type: openai
      model: anthropic/claude-3.5-sonnet
      params:
        base_url: https://openrouter.ai/api/v1
        api_key: $ENV:OPENROUTER_API_KEY
    gpt-4o-mini:
      type: openai
      model: openai/gpt-4o-mini
      params:
        base_url: https://openrouter.ai/api/v1
        api_key: $ENV:OPENROUTER_API_KEY
    o1-mini:
      type: openai
      model: openai/o1-mini
      params:
        base_url: https://openrouter.ai/api/v1
        api_key: $ENV:OPENROUTER_API_KEY
    o3-mini:
      type: openai
      model: openai/o3-mini
      params:
        base_url: https://openrouter.ai/api/v1
        api_key: $ENV:OPENROUTER_API_KEY
  glob_ignore:
    - _test.go
